export const CHECKOUT_FORM_INPUT_NAMES = {
  departureDate: 'departure-date',
  returnDate: 'return-date',
  originId: 'origin-id',
  originQuery: 'origin-query',
  numberOfRooms: 'number-of-rooms',
  roomQuantities: 'room-quantities',
  hotelId: 'hotel-id',
  roomId: 'room-id',
  people: 'people',
  departureFlightId: 'departure-flight-id',
  returnFlightId: 'return-flight-id',
  name: 'name',
  lastName: 'last-name',
  document: 'document',
  birthDate: 'birth-date',
  personRoom: 'person-room',
  tourId: 'tour-id',
}
