apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-


patchesStrategicMerge:
- ingress.yaml

images:
- name: smiles-api
  newName: us-west2-docker.pkg.dev/outsmart-development/images/smiles-api-staging
  newTag: 1631610833707521f4954b45381c5bb711c1ba8b
resources:
- ../base
