apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
- ../../base

patchesStrategicMerge:
- ingress.yaml

images:
- name: smiles-web
  newName: 186262579074.dkr.ecr.us-east-1.amazonaws.com/smiles-viagens-web
  newTag: dev-952ac3435e5cff98a2c0d148c18bdd72626c1345
