export enum InfoteraFlightSegmentClass {
  ECONOMIC = 'ECONOMIC',
  ECONOMIC_PREMIUM = 'ECONOMIC_PREMIUM',
  EXECUTIVE = 'EXECUTIVE',
  FIRST_CLASS = 'FIRST_CLASS',
  EXECUTIVE_PREMIUM = 'EXECUTIVE_PREMIUM',
  FIRST_CLASS_PREMIUM = 'FIRST_CLASS_PREMIUM',
  PREMIUM = 'PREMIUM',
  UNDEFINED = 'UNDEFINED',
}
