export enum InfotravelDiscountType {
  AGE = 'AGE',
  PROMOTION = 'PROMOTION',
  ADJUSTMENT = 'ADJUSTMENT',
  ANTICIPATION = 'ANTICIPATION',
  PAYMENT = 'PAYMENT',
  INSTALLMENT = 'INSTALLMENT',
  COUPON = 'COUPON',
  BUY_AND_RECEIVE = 'BUY_AND_RECEIVE',
  MANAGER = 'MANAGER',
  CLIENT_B2C = 'CLIENT_B2C',
  COMMISSION_ADJUSTMENT = 'COMMISSION_ADJUSTMENT',
  MARKUP_ADJUSTMENT = 'MARKUP_ADJUSTMENT',
}
