apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smiles-api
spec:
  ingressClassName: kong
  rules:
  - host: api-smiles.outsmartdigital.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smiles-api-service
            port:
              number: 8080
