name: nextjs-smiles

on:
  push:
    branches:
      - staging
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_PATH: us-west2-docker.pkg.dev
      IMAGE_NAME: 'smiles-api-${{github.ref_name}}'
      PROJECT_ID: outsmart-development
      ENVIRONMENT: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
      GKE_NS: ${{ github.ref_name == 'main' && 'smiles' || 'smiles-hm' }}
      GKE_CLUSTER: smiles-cluster-staging
      GKE_ZONE: southamerica-east1-a
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

    - uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}

    - run: |-
        gcloud --quiet auth configure-docker

    - uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Create secret with env
      run: |-
        touch env.txt
        echo '${{ secrets[env.ENVIRONMENT] }}' >> env.txt
        bash ./iac/scripts/create-secret-env.sh -f env.txt -n $GKE_NS

    - name: Build Docker Image
      run: docker build -f ./.docker/Dockerfile -t $IMAGE_NAME:latest .

    - name: Automatic Tagging of Releases
      if: "${{ github.ref_name == 'main' }}"
      id: increment-git-tag
      run: |
        bash ./iac/scripts/git_update.sh -v patch

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker $IMAGE_PATH --quiet
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ github.ref_name == 'main' && steps.increment-git-tag.outputs.git-tag || github.sha }}
      run: |-
        docker tag $IMAGE_NAME:latest $IMAGE_PATH/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest $IMAGE_PATH/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker push $IMAGE_PATH/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push $IMAGE_PATH/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"

    - name: Update Kubernetes resources
      env:
        GIT_TAG: ${{ github.ref_name == 'main' && steps.increment-git-tag.outputs.git-tag || github.sha }}
      run: |
        cd iac/argo-cd/$ENVIRONMENT
        kustomize edit set image smiles-api=$IMAGE_PATH/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG

    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull
        git commit -am "ci: bump docker version"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: outsmartdigital/smiles-monolith
        branch: ${{ github.ref }}
